indentation: 2
opt_in_rules:
- conditional_returns_on_newline
- force_unwrapping
- closure_spacing
- unneeded_parentheses_in_closure_argument
- vertical_whitespace_closing_braces

included:
- PKDB

excluded:
- PKDB/API.swift

identifier_name:
  excluded:
    - id

large_tuple:
  warning: 5
  error: 6
